<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Travel Statistics - {{ $user->name }}</title>
    <style>
        body { font-family: sans-serif; color: #333; }
        h1 { color: #1a202c; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
        h2 { font-size: 18px; margin-top: 20px; color: #4a5568; }
        .stats-grid { width: 100%; margin-bottom: 20px; }
        .stat-card { float: left; width: 48%; background: #f7fafc; padding: 15px; margin-bottom: 10px; border-radius: 5px; box-sizing: border-box; }
        .stat-card:nth-child( odd ) { margin-right: 2%; }
        .clear { clear: both; }
        .stat-value { font-size: 24px; font-weight: bold; color: #2d3748; }
        .stat-label { font-size: 14px; color: #718096; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #e2e8f0; padding: 8px; text-align: left; }
        th { background-color: #edf2f7; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 12px; color: #a0aec0; }
    </style>
</head>
<body>
    <h1>Travel Statistics Report</h1>
    <p>Generated for: <strong>{{ $user->name }}</strong> on {{ $generated_at->format('F j, Y') }}</p>

    <div class="stats-grid">
        <div class="stat-card">
            <div class="stat-label">Total Trips</div>
            <div class="stat-value">{{ $stats['total_trips'] ?? 0 }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-label">Countries Visited</div>
            <div class="stat-value">{{ $stats['unique_countries'] ?? 0 }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-label">Total Travel Days</div>
            <div class="stat-value">{{ $stats['total_travel_days'] ?? 0 }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-label">Total Budget Spent</div>
            <div class="stat-value">${{ number_format($stats['total_budget_spent'] ?? 0, 2) }}</div>
        </div>
        <div class="clear"></div>
    </div>

    <h2>Trip Status Distribution</h2>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['status_distribution'] as $status => $count)
                <tr>
                    <td>{{ $status }}</td>
                    <td>{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Top Destinations</h2>
    <table>
        <thead>
            <tr>
                <th>Destination</th>
                <th>Visits</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stats['top_destinations'] ?? [] as $dest)
                <tr>
                    <td>{{ $dest->destination }}</td>
                    <td>{{ $dest->count }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">No data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by Smart Travel Planner
    </div>
</body>
</html>
